#!/bin/bash
ESLINT_FORMAT="${ESLINT_FORMAT:-stylish}"
ESLINT_ENV="${ESLINT_ENV:-node}"
npm run --silent --prefix $(dirname $0) eslint -- --env $ESLINT_ENV --format $ESLINT_FORMAT -c package.json /usr/src/app
