#!/bin/bash

LINTER_HOME=$(dirname $0)

$LINTER_HOME/node_modules/.bin/stylelint "/usr/src/app/**/*.css" --config $LINTER_HOME/.stylelintrc && $LINTER_HOME/node_modules/.bin/htmlhint "/usr/src/app/**/*.html" --config $LINTER_HOME/.htmlhintrc
