#!/bin/sh

LINTER_HOME=$(dirname $0)

RULESET=/usr/src/app/ruff.toml

if [ -f $RULESET ]
then
  $LINTER_HOME/lib/bin/ruff check /usr/src/app --config=$RULESET
else
  $LINTER_HOME/lib/bin/ruff check /usr/src/app --config=$LINTER_DIR/ruff.toml
fi
