#!/bin/bash

export COMPOSER_NO_INTERACTION=1
PHPCS_FORMAT="${PHPCS_FORMAT:-full}"
LINTER_HOME=$(dirname $0)

RULESET=/usr/src/app/ruleset.xml

if [ ! -f $RULESET ]
then
    RULESET=
fi

xmlmerge --header --compact -o /tmp/phpcs.xml phpcs.xml $RULESET

$LINTER_HOME/vendor/bin/phpcs -- --standard=/tmp/phpcs.xml --report=$PHPCS_FORMAT -s /usr/src/app
